---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_license: accept-no-persist
  client_rb:
    chef_license: accept

platforms:
  - name: ubuntu-18.04

suites:
  - name: apache2
    run_list:
      - recipe[cachethq::install]
      - recipe[cachethq::apache2]
    attributes:

  - name: nginx
    run_list:
      - recipe[cachethq::install]
      - recipe[cachethq::nginx]
    attributes:
